/**
 * aiPatchScopeGuard — the constrained-AI contract for in-builder edits.
 *
 * AI is a designer inside the canonical path, never a file writer that can
 * reshape the platform. `commitMutation` remains the only durable writer;
 * this guard runs *before* it and rejects any AI-sourced patch that reaches
 * outside the surfaces AI is allowed to author:
 *
 *   allowed  — page bodies (/src/pages/**), section modules
 *              (/src/sections/**, /src/components/sections/**) and the
 *              generated style bridge for token-level design work.
 *   denied   — the deterministic router (/src/App.tsx), the runtime entry
 *              (/src/main.tsx), Unison canonical modules, Supabase
 *              integrations, and anything outside /src.
 *
 * This is a scope authority only. It does not compile, seal, or persist —
 * those stay with the canonical pipeline (Stage 4b → preflight → seal →
 * commitMutation).
 */

import { isUnisonProtectedPath } from '@/services/unisonCanonicalRegistry';

/** Paths AI may never create, replace, or delete. */
const DENIED_EXACT = new Set<string>([
  '/src/App.tsx',
  '/src/main.tsx',
  '/index.html',
  '/package.json',
  '/vite.config.ts',
  '/tailwind.config.ts',
]);

const DENIED_PREFIXES = [
  '/src/integrations/',
  '/src/platform/',
  '/src/services/',
  '/supabase/',
  '/.unison/',
];

/** Surfaces AI is allowed to author. */
const ALLOWED_PREFIXES = [
  '/src/pages/',
  '/src/sections/',
  '/src/components/sections/',
  '/src/styles/',
];

/** Files AI may author outside the allowed prefixes (token/design bridge). */
const ALLOWED_EXACT = new Set<string>([
  '/src/index.css',
  '/src/generated/styleBridge.ts',
]);

export interface AiPatchScopeViolation {
  path: string;
  reason: string;
}

export interface AiPatchScopeResult {
  allowed: boolean;
  violations: AiPatchScopeViolation[];
  /** Paths the patch legitimately changes. */
  changedPaths: string[];
}

function normalize(path: string): string {
  const trimmed = (path ?? '').trim();
  if (!trimmed) return '';
  return trimmed.startsWith('/') ? trimmed : `/${trimmed}`;
}

function violationFor(path: string): string | null {
  if (!path) return 'empty path';
  if (DENIED_EXACT.has(path)) return 'canonical platform file — owned by the deterministic compiler';
  if (isUnisonProtectedPath(path)) return 'Unison canonical module — regenerated by the pipeline';
  for (const prefix of DENIED_PREFIXES) {
    if (path.startsWith(prefix)) return `outside AI authoring scope (${prefix}*)`;
  }
  if (ALLOWED_EXACT.has(path)) return null;
  for (const prefix of ALLOWED_PREFIXES) {
    if (path.startsWith(prefix)) return null;
  }
  return 'not a page body, section module, or design-token surface';
}

/**
 * Compare the AI's proposed file map against the working VFS and validate
 * every path it actually changes. Unchanged files are ignored: AI callers
 * routinely resend the whole map.
 */
export function checkAiPatchScope(
  beforeFiles: Record<string, string>,
  nextFiles: Record<string, string>,
): AiPatchScopeResult {
  const violations: AiPatchScopeViolation[] = [];
  const changedPaths: string[] = [];

  const paths = new Set<string>([...Object.keys(beforeFiles ?? {}), ...Object.keys(nextFiles ?? {})]);
  for (const raw of paths) {
    const path = normalize(raw);
    const before = beforeFiles?.[raw];
    const next = nextFiles?.[raw];
    // Deletion is only a real change when the AI map is authoritative for
    // that path; a partial map simply omits files it did not touch.
    if (next === undefined) continue;
    if (before === next) continue;
    changedPaths.push(path);
    const reason = violationFor(path);
    if (reason) violations.push({ path, reason });
  }

  return { allowed: violations.length === 0, violations, changedPaths };
}

export function describeAiPatchScopeViolations(violations: AiPatchScopeViolation[]): string {
  if (violations.length === 0) return '';
  const head = violations
    .slice(0, 3)
    .map((v) => `${v.path} (${v.reason})`)
    .join('; ');
  const rest = violations.length > 3 ? ` and ${violations.length - 3} more` : '';
  return `AI edits are limited to page and section design surfaces. Rejected: ${head}${rest}.`;
}
