import { z } from 'zod';
export const briefSchema = z.object({
  businessName: z.string().max(300), industry: z.string().max(100),
  launchSeed: z.string().max(150), vision: z.string().max(8000).optional(),
  goal: z.string().max(100).optional(), needs: z.array(z.string().max(100)).max(30).optional(),
  roles: z.array(z.string().max(40)).min(1).max(14), pack: z.string().max(80),
  variants: z.array(z.object({ id: z.string().max(100), family: z.string().max(40),
    description: z.string().max(1200), pageRoles: z.array(z.string().max(40)).max(14),
    preferredSource: z.boolean(), certification: z.string().max(40),
    tags: z.array(z.string().max(80)).max(30).optional(),
    // Provenance of the certified implementation (origin registry + author) and
    // its thumbnail, so the composer can reason about presentation quality.
    origin: z.string().max(40).optional(), author: z.string().max(120).optional(),
    sourceUrl: z.string().max(400).optional(), thumbnail: z.string().max(300).optional(),
    generationStatus: z.string().max(40).optional(),
    visualSignature: z.object({
      geometry: z.enum(['centered','split','asymmetric','full-bleed','layered','spatial']),
      mediaDominance: z.enum(['low','medium','high']), typographyScale: z.enum(['restrained','display','monumental']),
      density: z.enum(['airy','balanced','dense']), motion: z.array(z.string().max(100)).max(20),
      composition: z.string().max(1200), experienceLevel: z.enum(['standard','motion-rich','immersive']),
    }).strict().optional(),
  }).strict()).min(1).max(300),
  designSelection: z.object({ mode: z.enum(['auto','guided','custom']), artDirectionPackId: z.string().max(80),
    experience: z.enum(['standard','motion-rich','immersive']), pinnedVariants: z.record(z.string(), z.string().max(100)) }).strict().optional(),
  assets: z.array(z.object({ id: z.string().max(150), kind: z.string().max(30), name: z.string().max(300),
    url: z.string().max(4000), width: z.number().optional(), height: z.number().optional(),
    tags: z.array(z.string().max(80)).max(12), }).strict()).max(40).optional(),
  runtimeDependencies: z.record(z.string(), z.string()).optional(),
  primitiveFamilies: z.array(z.object({ family: z.string().max(40), values: z.array(z.string().max(120)).max(100) }).strict()).max(10).optional(),
  capabilityRequirements: z.array(z.object({ id: z.string().max(80), requiredTables: z.array(z.string().max(100)).max(30),
    supportedSlots: z.array(z.string().max(150)).max(60), providedIntents: z.array(z.string().max(150)).max(60) }).strict()).max(20).optional(),
  implementationContracts: z.array(z.object({ id: z.string().max(100), sectionType: z.string().max(50),
    runtimeDependencies: z.array(z.string().max(150)).max(40).optional(), componentStates: z.unknown().optional(),
    visualSignature: z.unknown().optional(), compatibleExperiencePreferences: z.array(z.enum(['standard','motion-rich','immersive'])).max(3).optional(),
    artifactContract: z.unknown().optional() }).strict()).max(300).optional(),
  canonicalContract: z.string().max(40000).optional(),
  task: z.string().max(1000).optional(), designGuidance: z.string().max(2000).optional(),
  constraints: z.string().max(3000).optional(), output: z.unknown().optional(),
}).strict();
