/**
 * Host-side ProductCard
 * --------------------------------------------------------------
 * Thin wrapper over the canonical unison product bindings.
 * Mirrors the API of `@/unison/products` (the VFS-resident module
 * generated by `unisonProductsGenerator`) so that host previews,
 * inspectors, and editor surfaces render the exact same card the
 * generated site renders — driven by CreatorData, not hardcoded
 * arrays.
 */
import React, { useMemo } from 'react';
import { ShoppingCart, Star } from 'lucide-react';
import type { CreatorData, CreatorProduct } from '@/types/creatorData';
import { buildUnisonData } from '@/services/unisonDataGenerator';
import { useTemplateAutomation } from '@/hooks/useTemplateAutomation';

type ResolvedProduct = CreatorProduct & { inStock: boolean; imageUrl?: string };

export interface ProductCardProps {
  /** Required: id (or slug) of the product to render from CreatorData. */
  productId: string;
  /** Canonical CreatorData payload (typically from useCreatorPlayground). */
  creatorData: CreatorData;
  showAddToCart?: boolean;
  className?: string;
  /** Optional accent — defaults to the design-system primary token. */
  primaryColor?: string;
  onAddToCart?: () => void;
}

function formatPrice(p: ResolvedProduct): string {
  const currency = p.currency || 'USD';
  try {
    return new Intl.NumberFormat(undefined, { style: 'currency', currency }).format(p.price ?? 0);
  } catch {
    return `$${(p.price ?? 0).toFixed(2)}`;
  }
}

function availabilityLabel(p: ResolvedProduct): string | null {
  if (p.status === 'draft') return 'Draft';
  if (p.status === 'archived') return 'Archived';
  if (!p.inStock) return 'Out of stock';
  if (
    p.trackInventory &&
    typeof p.stockQuantity === 'number' &&
    typeof p.lowStockThreshold === 'number' &&
    p.stockQuantity <= p.lowStockThreshold
  ) {
    return `Only ${p.stockQuantity} left`;
  }
  return null;
}

export const ProductCard: React.FC<ProductCardProps> = ({
  productId,
  creatorData,
  showAddToCart = true,
  className,
  primaryColor,
  onAddToCart,
}) => {
  const { addToCart, loading } = useTemplateAutomation();

  const product = useMemo<ResolvedProduct | undefined>(() => {
    const data = buildUnisonData(creatorData);
    return data.products.find(
      (p) => p.productId === productId || p.slug === productId,
    ) as ResolvedProduct | undefined;
  }, [creatorData, productId]);

  if (!product) {
    return (
      <div className="rounded-lg border border-dashed border-muted-foreground/30 p-4 text-sm text-muted-foreground">
        Product "{productId}" not found in catalog.
      </div>
    );
  }

  const badge = availabilityLabel(product);
  const disabled = !product.inStock || product.status === 'archived' || product.status === 'draft';

  const handleAddToCart = async () => {
    if (disabled) return;
    await addToCart(product.productId);
    onAddToCart?.();
  };

  const accent = primaryColor;

  return (
    <div
      className={`group overflow-hidden rounded-xl border border-border bg-card text-card-foreground shadow-sm transition hover:shadow-md ${className ?? ''}`}
      data-ut-product-id={product.productId}
      data-ut-source-table="products"
      data-ut-row-id={product.productId}
    >
      <div className="relative aspect-square bg-muted">
        {product.imageUrl ? (
          <img
            src={product.imageUrl}
            alt={product.name}
            className="h-full w-full object-cover transition-transform duration-300 group-hover:scale-105"
            loading="lazy"
          />
        ) : (
          <div className="flex h-full w-full items-center justify-center text-xs text-muted-foreground">
            No image
          </div>
        )}
        {product.category ? (
          <span className="absolute left-2 top-2 rounded bg-background/80 px-2 py-1 text-xs backdrop-blur-sm">
            {product.category}
          </span>
        ) : null}
        {badge ? (
          <span className="absolute right-2 top-2 rounded bg-background/80 px-2 py-1 text-xs font-medium backdrop-blur-sm">
            {badge}
          </span>
        ) : null}
      </div>
      <div className="p-4">
        <h3 className="truncate font-semibold">{product.name}</h3>
        {product.description ? (
          <p className="mt-1 line-clamp-2 text-sm text-muted-foreground">{product.description}</p>
        ) : null}
        <div className="mt-2 flex items-center gap-1">
          {Array.from({ length: 5 }).map((_, i) => (
            <Star
              key={i}
              className={`h-3 w-3 ${i < 4 ? 'fill-yellow-400 text-yellow-400' : 'text-muted-foreground/40'}`}
            />
          ))}
        </div>
        <div className="mt-4 flex items-center justify-between gap-2">
          <span
            className="text-lg font-bold"
            style={accent ? { color: accent } : undefined}
          >
            {formatPrice(product)}
          </span>
          {showAddToCart ? (
            <button
              type="button"
              data-ut-intent="commerce.addToCart"
              data-ut-product-id={product.productId}
              data-ut-source-table="products"
              data-ut-row-id={product.productId}
              disabled={disabled || loading}
              onClick={handleAddToCart}
              className="inline-flex items-center gap-1 rounded-md bg-primary px-3 py-1.5 text-sm font-medium text-primary-foreground transition hover:opacity-90 disabled:cursor-not-allowed disabled:opacity-50"
              style={accent ? { backgroundColor: accent } : undefined}
            >
              <ShoppingCart className="h-4 w-4" />
              Add
            </button>
          ) : null}
        </div>
      </div>
    </div>
  );
};

export default ProductCard;
