-- Full-Stack AI Generated Applications
-- Store complete applications generated by AI with database schema, backend, and frontend

-- Generated Applications table
CREATE TABLE IF NOT EXISTS generated_applications (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    
    -- Ownership
    project_id UUID REFERENCES projects(id) ON DELETE CASCADE,
    workspace_id UUID,
    user_id UUID REFERENCES auth.users(id),
    
    -- Application details
    name TEXT NOT NULL,
    description TEXT,
    type TEXT NOT NULL CHECK (type IN ('dashboard', 'crm', 'settings', 'admin', 'portal', 'saas', 'custom')),
    
    -- Configuration (full JSON config)
    config JSONB NOT NULL,
    
    -- Generated files
    files JSONB DEFAULT '[]'::jsonb, -- Array of {path, content, type}
    
    -- Preview
    preview_html TEXT, -- Self-contained HTML for live preview
    preview_url TEXT, -- Deployed preview URL
    
    -- Database schema
    database_schema JSONB, -- Array of table definitions
    database_migrated BOOLEAN DEFAULT false,
    
    -- Backend API
    backend_endpoints JSONB, -- Array of API endpoint definitions
    backend_deployed BOOLEAN DEFAULT false,
    
    -- Frontend
    frontend_framework TEXT DEFAULT 'react',
    frontend_deployed BOOLEAN DEFAULT false,
    
    -- Features
    features TEXT[] DEFAULT '{}',
    has_authentication BOOLEAN DEFAULT false,
    has_database BOOLEAN DEFAULT false,
    has_backend BOOLEAN DEFAULT false,
    
    -- Deployment
    deployment_status TEXT DEFAULT 'draft' CHECK (deployment_status IN ('draft', 'deploying', 'deployed', 'failed')),
    deployment_platform TEXT,
    deployment_url TEXT,
    deployment_error TEXT,
    
    -- Versioning
    version INTEGER DEFAULT 1,
    parent_id UUID REFERENCES generated_applications(id), -- For versioning
    
    -- Status
    is_active BOOLEAN DEFAULT true,
    is_public BOOLEAN DEFAULT false,
    
    -- Analytics
    views_count INTEGER DEFAULT 0,
    forks_count INTEGER DEFAULT 0,
    
    -- Metadata
    tags TEXT[] DEFAULT '{}',
    metadata JSONB DEFAULT '{}'::jsonb,
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    deployed_at TIMESTAMP WITH TIME ZONE
);

-- Application components (for modular apps)
CREATE TABLE IF NOT EXISTS app_components (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    application_id UUID NOT NULL REFERENCES generated_applications(id) ON DELETE CASCADE,
    
    -- Component details
    name TEXT NOT NULL,
    type TEXT NOT NULL, -- 'page', 'component', 'layout', 'utility'
    path TEXT NOT NULL, -- File path in project
    
    -- Code
    code TEXT NOT NULL,
    language TEXT DEFAULT 'typescript',
    
    -- Dependencies
    dependencies TEXT[] DEFAULT '{}',
    imports TEXT[] DEFAULT '{}',
    
    -- Props/Interface
    props_schema JSONB,
    
    -- Data binding
    data_source JSONB, -- {type, endpoint, query, etc}
    
    -- Styling
    css TEXT,
    tailwind_classes TEXT,
    
    -- Metadata
    description TEXT,
    tags TEXT[] DEFAULT '{}',
    is_reusable BOOLEAN DEFAULT true,
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Application data sources (for data-driven apps)
CREATE TABLE IF NOT EXISTS app_data_sources (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    application_id UUID NOT NULL REFERENCES generated_applications(id) ON DELETE CASCADE,
    
    -- Data source details
    name TEXT NOT NULL,
    type TEXT NOT NULL CHECK (type IN ('api', 'database', 'static', 'computed', 'realtime')),
    
    -- Configuration
    config JSONB NOT NULL,
    
    -- API source
    endpoint TEXT,
    method TEXT,
    headers JSONB,
    
    -- Database source
    table_name TEXT,
    query TEXT,
    
    -- Static data
    data JSONB,
    
    -- Computed source
    computation TEXT,
    
    -- Caching
    cache_enabled BOOLEAN DEFAULT false,
    cache_duration INTEGER, -- seconds
    
    -- Transform
    transform_function TEXT,
    
    -- Status
    is_active BOOLEAN DEFAULT true,
    last_sync TIMESTAMP WITH TIME ZONE,
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Application deployments (deployment history)
CREATE TABLE IF NOT EXISTS app_deployments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    application_id UUID NOT NULL REFERENCES generated_applications(id) ON DELETE CASCADE,
    
    -- Deployment details
    version INTEGER NOT NULL,
    platform TEXT NOT NULL, -- 'vercel', 'netlify', 'supabase', etc
    
    -- URLs
    url TEXT,
    preview_url TEXT,
    
    -- Status
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'building', 'deployed', 'failed', 'rolled_back')),
    
    -- Build info
    build_id TEXT,
    build_log TEXT,
    build_duration INTEGER, -- seconds
    
    -- Environment
    environment TEXT DEFAULT 'production', -- 'production', 'staging', 'preview'
    environment_variables JSONB,
    
    -- Deployment config
    config JSONB,
    
    -- Error tracking
    error_message TEXT,
    error_details JSONB,
    
    -- User
    deployed_by UUID REFERENCES auth.users(id),
    
    -- Timestamps
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    completed_at TIMESTAMP WITH TIME ZONE
);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_generated_applications_project ON generated_applications(project_id);
CREATE INDEX IF NOT EXISTS idx_generated_applications_workspace ON generated_applications(workspace_id);
CREATE INDEX IF NOT EXISTS idx_generated_applications_user ON generated_applications(user_id);
CREATE INDEX IF NOT EXISTS idx_generated_applications_type ON generated_applications(type);
CREATE INDEX IF NOT EXISTS idx_generated_applications_status ON generated_applications(deployment_status);
CREATE INDEX IF NOT EXISTS idx_generated_applications_active ON generated_applications(is_active);

CREATE INDEX IF NOT EXISTS idx_app_components_application ON app_components(application_id);
CREATE INDEX IF NOT EXISTS idx_app_components_type ON app_components(type);
CREATE INDEX IF NOT EXISTS idx_app_components_reusable ON app_components(is_reusable);

CREATE INDEX IF NOT EXISTS idx_app_data_sources_application ON app_data_sources(application_id);
CREATE INDEX IF NOT EXISTS idx_app_data_sources_type ON app_data_sources(type);
CREATE INDEX IF NOT EXISTS idx_app_data_sources_active ON app_data_sources(is_active);

CREATE INDEX IF NOT EXISTS idx_app_deployments_application ON app_deployments(application_id);
CREATE INDEX IF NOT EXISTS idx_app_deployments_status ON app_deployments(status);
CREATE INDEX IF NOT EXISTS idx_app_deployments_environment ON app_deployments(environment);

-- Row Level Security
ALTER TABLE generated_applications ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_components ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_data_sources ENABLE ROW LEVEL SECURITY;
ALTER TABLE app_deployments ENABLE ROW LEVEL SECURITY;

-- Policies for generated_applications
CREATE POLICY "Users can view their own applications"
    ON generated_applications FOR SELECT
    USING (auth.uid() = user_id OR is_public = true);

CREATE POLICY "Users can create applications"
    ON generated_applications FOR INSERT
    WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own applications"
    ON generated_applications FOR UPDATE
    USING (auth.uid() = user_id);

CREATE POLICY "Users can delete their own applications"
    ON generated_applications FOR DELETE
    USING (auth.uid() = user_id);

-- Policies for app_components
CREATE POLICY "Users can view components of their applications"
    ON app_components FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM generated_applications 
            WHERE id = app_components.application_id 
            AND (user_id = auth.uid() OR is_public = true)
        )
    );

CREATE POLICY "Users can manage components of their applications"
    ON app_components FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM generated_applications 
            WHERE id = app_components.application_id 
            AND user_id = auth.uid()
        )
    );

-- Policies for app_data_sources
CREATE POLICY "Users can view data sources of their applications"
    ON app_data_sources FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM generated_applications 
            WHERE id = app_data_sources.application_id 
            AND (user_id = auth.uid() OR is_public = true)
        )
    );

CREATE POLICY "Users can manage data sources of their applications"
    ON app_data_sources FOR ALL
    USING (
        EXISTS (
            SELECT 1 FROM generated_applications 
            WHERE id = app_data_sources.application_id 
            AND user_id = auth.uid()
        )
    );

-- Policies for app_deployments
CREATE POLICY "Users can view deployments of their applications"
    ON app_deployments FOR SELECT
    USING (
        EXISTS (
            SELECT 1 FROM generated_applications 
            WHERE id = app_deployments.application_id 
            AND user_id = auth.uid()
        )
    );

CREATE POLICY "Users can create deployments for their applications"
    ON app_deployments FOR INSERT
    WITH CHECK (
        EXISTS (
            SELECT 1 FROM generated_applications 
            WHERE id = application_id 
            AND user_id = auth.uid()
        )
    );

-- Updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = NOW();
    RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_generated_applications_updated_at
    BEFORE UPDATE ON generated_applications
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_app_components_updated_at
    BEFORE UPDATE ON app_components
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_app_data_sources_updated_at
    BEFORE UPDATE ON app_data_sources
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_app_deployments_updated_at
    BEFORE UPDATE ON app_deployments
    FOR EACH ROW
    EXECUTE FUNCTION update_updated_at_column();

-- Comments
COMMENT ON TABLE generated_applications IS 'AI-generated full-stack applications with database, backend, and frontend';
COMMENT ON TABLE app_components IS 'Modular components within generated applications';
COMMENT ON TABLE app_data_sources IS 'Data sources and APIs used by applications';
COMMENT ON TABLE app_deployments IS 'Deployment history and status for applications';
