// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { createAuthRecoveryFetch } from './authSessionRecovery';

import { SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, isSupabaseEnvConfigured } from './env';

const supabaseFetch = createAuthRecoveryFetch(async () => {
	// Only a rejected refresh credential clears the local session.
	await supabase.auth.signOut({ scope: 'local' });
});

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
	auth: {
		autoRefreshToken: true,
		persistSession: true,
		detectSessionInUrl: true,
	},
	global: {
		fetch: supabaseFetch,
	},
	// Local and deployed sessions subscribe to the same authenticated Cloud feed.
	realtime: {},
});

// Export configuration status flag
export const isSupabaseConfigured = isSupabaseEnvConfigured;
